kind: pipeline
type: kubernetes
name: default
clone:
  disable: true

steps:
  - name: clone
    image: wwma/drone-github-clone
    settings:
      SSH_KEY:
        from_secret: ssh_key

  - name: build_docker
    depends_on: [ clone ]
    image: plugins/docker:latest
    pull: if-not-exists
    settings:
      registry: hub.ooxo.cc
      username:
        from_secret: nexus_docker_username
      password:
        from_secret: nexus_docker_password
      repo: hub.ooxo.cc/home/stock-analysis-engine # Changed to stock-analysis-engine
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest

  - name: deploy_to_k8s
    image: appleboy/drone-ssh
    depends_on:
      - build_docker
    settings:
      host:
        from_secret: k8s_host
      username:
        from_secret: k8s_username
      key:
        from_secret: k8s_key
      port: 22
      command_timeout: 2m
      script:
        - kubectl apply -f deployment.yaml # Apply your deployment YAML
        - kubectl apply -f service.yaml   # Apply your service YAML
        - kubectl set image deployment/stock-analysis-engine stock-analysis-engine=hub.ooxo.cc/home/stock-analysis-engine:${DRONE_COMMIT_SHA:0:8} # Update stock-analysis-engine deployment
